#!/usr/bin/env python3
"""
Regex-ing
"""

import re


def filter_datum(fields, redaction, message, separator):
    """
    a function called filter_datum that returns the log message obfuscated:
    """
    return re.sub(fr'(?<={separator}|^)({"|".join(fields)})=(.*?)(?={separator}|$)', f'\\1={redaction}', message)
